auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: starcroce
url: http://starcroce.github.io
feed: /atom.xml
author_info: <a href="http://starcroce.github.io/">starcroce</a>
